import { products } from "@/lib/products";

export function InventoryPanel({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;
  const physical = products.reduce((s, p) => s + p.stock, 0);
  const reserved = products.reduce((s, p) => s + p.reserved, 0);
  const low = products.filter(p => p.stock - p.reserved <= 5);
  return <div className="admin-shell"><header className="admin-header"><div><span className="admin-logo">Fanny</span><span>Painel operacional · demonstração</span></div><button onClick={onClose}>Voltar à loja ×</button></header><main className="admin-main"><div className="admin-heading"><div><span className="eyebrow">Estoque e operação</span><h1>Visão geral</h1><p>Controle por SKU, reserva, lote e validade usando a regra FEFO.</p></div><button className="primary-button">+ Entrada de estoque</button></div><div className="stat-grid"><article><span>SKUs ativos</span><strong>{products.length}</strong><small>catálogo demonstrativo</small></article><article><span>Estoque físico</span><strong>{physical}</strong><small>unidades totais</small></article><article><span>Reservado</span><strong>{reserved}</strong><small>checkout e pedidos</small></article><article className="warning"><span>Estoque baixo</span><strong>{low.length}</strong><small>requer atenção</small></article></div><section className="inventory-card"><div className="inventory-title"><div><h2>Posição de estoque</h2><p>Disponível = físico − reservado − bloqueado.</p></div><input placeholder="Buscar SKU ou produto" aria-label="Buscar no estoque" /></div><div className="table-wrap"><table><thead><tr><th>Produto</th><th>SKU</th><th>Físico</th><th>Reservado</th><th>Disponível</th><th>Lote</th><th>Validade</th><th>Status</th></tr></thead><tbody>{products.map(p => { const available = p.stock - p.reserved; return <tr key={p.id}><td><strong>{p.name}</strong><small>{p.brand}</small></td><td>{p.sku}</td><td>{p.stock}</td><td>{p.reserved}</td><td><strong>{available}</strong></td><td>{p.lot}</td><td>{new Date(p.expiresAt).toLocaleDateString("pt-BR")}</td><td><span className={`stock-status ${available <= 5 ? "low" : "ok"}`}>{available <= 5 ? "Baixo" : "Saudável"}</span></td></tr>})}</tbody></table></div></section><section className="admin-bottom"><article><span className="eyebrow">Reposição sugerida</span><h2>{low.length} itens abaixo do nível confortável</h2><p>Crie um pedido de compra para evitar indisponibilidade dos produtos mais procurados.</p><button>Revisar sugestões →</button></article><article><span className="eyebrow">Boas práticas</span><h2>Sem estoque negativo</h2><p>Reservas devem ser transacionais, expirar automaticamente e gerar movimentações auditáveis.</p></article></section></main></div>;
}
